### ISSUE TITLE
geonames

### ISSUE THREAD

**Issue by benmarwick** [ropensci/maptools#14]
[Geonames](http://www.geonames.org/) seems like a relevant data source: 'an open-source geographical database, which you can download, that contains information on many types of features, in various languages, has attribute data (such as elevation) and comes with lat/long coordinates.' There is an R package [geonames](http://cran.r-project.org/web/packages/geonames/)

By the way, did you write the [tools.ctv](https://github.com/ropensci/maptools/blob/master/tools.ctv) file by hand? Or in some other format first and then process it to get all those tags? I'm asking because I've written a [ctv in markdown](https://github.com/benmarwick/ctv-archaeology) and am looking for some script to convert it to the regular ctv format. Thanks.

**Comment by jhollist** [comment]
@benmarwick [geonames](http://cran.r-project.org/web/packages/geonames/) is a nice addition.  Also the historical US boundaries ins #15 is certainly within scope.  A PR on both would be gladly accepted.

As for [tools.ctv](https://github.com/ropensci/maptools/blob/master/tools.ctv) that is edited and (I beieve) created by hand.  The workflow we use for this is borrowed from @sckott.  He used this for the   [web technologies](https://github.com/ropensci/webservices) task view.  Any more insight on this @sckott?

**Comment by sckott** [comment]
@benmarwick hey, that tools.ctv file is copy from the web tech task view. there is some mustache templating in that file, and the first thing done int the Makefile is process that file https://github.com/ropensci/maptools/blob/master/whiskerit.R#L7 

Basically the workflow I used was to start with a `.ctv` file (partly complete, see the mustache templates for the package links  at bottom of the `.ctv` file), then create markdown/html from that.

**Comment by sckott** [comment]
i can't claim this is the best way to do it :question:

**Comment by benmarwick** [comment]
Thanks for the pointers, I just came across this for md -> ctv, looks close to what I'm after: https://gist.github.com/ramnathv/6615277
