### ISSUE TITLE
Review 

### ISSUE THREAD

**Issue by jhollist** [ropensci/maptools#20]
@karthik and @sckott 

So after quite a while, I think I have a draft close.  

There is at least enough in here for a review of the language, layout, included packages, etc.  

Also, I'm not an svn guy so I'll need some help (or instructions) on pushing up to CRAN when we think we are done.

**Comment by sckott** [comment]
can do, and yes, can help with svn too.

**Comment by jhollist** [comment]
:+1:

**Comment by sckott** [comment]
To get it rolling wrt CRAN, you need to get membership on https://r-forge.r-project.org/projects/ctv/ then email Achim and ask to make sure he'll accept it, then it can be submitted. If you don't want to deal with submitting via svn I can do that part

**Comment by jhollist** [comment]
Thanks, will do that shortly.

Once we are done we can figure out the svn.  Might not be a bad thing for me to figure out.

**Comment by sckott** [comment]
Some thoughts:

* Looks great!
* I am working on a r wrapper to `proj.js`, include if you want, or not, no worries (https://github.com/ropensci/proj)
* I think @hadley said he was helping with a client for natural earth layers?
* Maybe could have a section for __base layers__? to include things like open street maps layers, all the layers behind leaflet.js, etc. 
* Maybe include a warning about using `leaflet` and `leafletR` together (e.g., problem https://github.com/ropensci/ecoengine/issues/85)
* I know Achime has been wanting us to avoid including pkgs only on Github (i.e., not on CRAN), but that seems a bit silly, i dont know how much he'll enforce that

**Comment by jhollist** [comment]
I did email Achim and have already heard back.  He pinged Roger and Edzer as he was a bit concerned about the overlap.  I'll need to chat with them before we can get this through.  They do include some viz and data source stuff is the Spatial task view.  A clean distinction between the two is going to take some work, I think.  

Also, would be nice to be able to inlcude github only packages, but I suppose it is a CRAN task view so makes some sense...

**Comment by jhollist** [comment]
closing this.

We had some discussions about this and given the overlap and our desire to include GitHub packages as well a CRAN task view may not be the best.  Need to have more discussions on how best to share this list/task view/etc with the world...
