### ISSUE TITLE
Add mapview

### ISSUE THREAD

**Issue by kent37** [ropensci/maptools#22]
Mapview is a wrapper around leaflet that lets you make an interactive map with one line of code. Very handy for exploratory visualizations. I suggest adding it to the visualization section.
https://cran.r-project.org/web/packages/mapview/index.html
http://environmentalinformatics-marburg.github.io/web-presentations/20150723_mapView.html

**Comment by jhollist** [comment]
@kent37 Good one!  I have seen `mapview`, but haven't had a chance to use it yet.  Definitely fits in with the maptools list.

I'll get it added in the next week or so.

**Comment by ateucher** [comment]
:+1: from me. I used it for the first time this week - it's super helpful!
