### ISSUE TITLE
Installing rgdal on mac

### ISSUE THREAD

**Issue by hadley** [ropensci/maptools#4]
Is that in scope for task view?  Would be useful to include some instructions

**Comment by jhollist** [comment]
I agree that this is useful information to collect somewhere, just not sure if this Task View is the place.  

Thinking of closing the issue, unless others feel strongly about including this in the task view.

**Comment by jhollist** [comment]
Finally getting back to some work on this.  I am going to go head and close.

I am certainly more than willing to re-visit the larger issue of dependencies for this task view
